name: Website Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch: #Allow manual triggers

jobs:
  deploy-s3-website:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI 
        run: |
          sudo apt-get update && sudo apt-get install -y awscli

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-west-1
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{secrets.AWS_SESSION_TOKEN }}

      - name: Get API outputs \
        run: |
          GET_API_URL=$(aws cloudformation describe-stacks --stack-name my-resume-cf-stack \
          --query "Stacks[0].Outputs[?OutputKey=='GetApiUrl'].OutputValue" --output text)
          echo "GET_API_URL=$GET_API_URL" >> $GITHUB_ENV
          POST_API_URL=$(aws cloudformation describe-stacks --stack-name my-resume-cf-stack \
          --query "Stacks[0].Outputs[?OutputKey=='PostApiUrl'].OutputValue" --output text)
          echo "POST_API_URL=$POST_API_URL" >> $GITHUB_ENV
          
      - name: Deploy S3 website 
        run: |
          MY_BUCKET="agneslimbi-resume.com"
          DISTRIBUTION_ID=E1OPWJOVC1QVAZ
          export GET_API_URL=$GET_API_URL
          export POST_API_URL=$POST_API_URL
         
          

          sed -i 's/__POST_API_URL___/'"$POST_API_URL"'/g' index.html
          sed -i 's/__GET_API_URL___/'"$GET_API_URL"'/g' index.html

          #upload index.html file and css style sheet  to s3 bucket
          aws s3 cp index.html s3://${MY_BUCKET}/index.html
          
          #invalidate cloudfront distribution 
          aws cloudfront create-invalidation --distribution-id E1OPWJOVC1QVAZ --paths "/index.html" "/style.css"
          echo "Distribution invalidated !!"
  
